---
- name: Install programs and dotfiles locally
  hosts: localhost
  collections:
    - community.general
  tasks:
    - import_tasks: ubuntu.yml
    - import_tasks: homebrew.yml
    - import_tasks: starship.yml
    - import_tasks: tilda/tilda.yml
    - import_tasks: topgrade.yml
    - import_tasks: gnome-shell.yml
