---
- name: Install programs and dotfiles locally
  hosts: localhost
  collections:
    - community.general
  vars:
    brew_packages:
      - ripgrep
      - starship
  tasks:
    - name: Install Ubuntu packages we want
      apt:
        name:
          - curl
          - firefox
          # Required for dconf step in ubuntu.yml
          - python3-psutil
          - tilda
          - vim
        state: present
      become: yes
    - name: Install Snap packages we want
      community.general.snap:
        name:
          - zoom-client
      become: yes
    - name: Remove Snap packages we do not want
      community.general.snap:
        name:
          # Firefox via Snap is super slow on cold starts, install the APT
          # version above instead.
          - firefox
        state: absent
      become: yes
    - import_tasks: homebrew.yml
    - import_tasks: starship.yml
    - import_tasks: tilda.yml
    - import_tasks: topgrade.yml
    - import_tasks: ubuntu.yml
