---
- name: Install programs and dotfiles locally
  hosts: localhost
  collections:
    - community.general
  vars:
    brew_packages:
      - ripgrep
      - starship
  tasks:
    - name: Install Ubuntu packages we want
      apt:
        name:
          - curl
          - vim
        state: present
      become: yes
    - import_tasks: homebrew.yml
    - import_tasks: starship.yml
    - import_tasks: topgrade.yml
