---
- name: Install programs and dotfiles locally
  hosts: localhost
  collections:
    - community.general
  vars:
    brew_packages:
      - starship
  tasks:
    - import_tasks: homebrew.yml
    - import_tasks: starship.yml
