---
- name: Remove APT packages we do not want
  apt:
    name:
      # The APT version of LibreOffice does not work with some extensions for
      # me, use the Snap version instead.
      - libreoffice-base-core
    state: absent
  become: yes

- name: Add Mozilla Team PPA for Firefox APT version
  apt_repository:
    repo: 'ppa:mozillateam/ppa'
  become: yes

- name: Set Firefox PPA priority to come first
  ansible.builtin.copy:
    content: |
      Package: *
      Pin: release o=LP-PPA-mozillateam
      Pin-Priority: 1001
    dest: /etc/apt/preferences.d/mozillateamppa
  become: yes
  register: firefox_ppa_prio

- name: Add Chrome signing key
  ansible.builtin.apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
  become: yes

- name: Add Google Chrome APT repository into sources list
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome
  become: yes

- name: Add Git PPA to get autoSetupRemote support
  apt_repository:
    repo: 'ppa:git-core/ppa'
  become: yes

- name: Add DDEV signing key
  ansible.builtin.apt_key:
    url: https://apt.fury.io/drud/gpg.key
    keyring: /etc/apt/trusted.gpg.d/ddev.gpg
  become: yes

- name: Add DDEV APT repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://apt.fury.io/drud/ * *
    state: present
    filename: ddev
  become: yes

- name: Add yt-dlp PPA
  apt_repository:
    repo: 'ppa:yt-dlp/stable'
  become: yes

- name: Install Ubuntu packages we want
  apt:
    name:
      # Used for automatic background updates, see
      # https://klau.si/blog/fully-hidden-automatic-system-updates-ubuntu/
      - anacron
      - build-essential
      - curl
      - ddev
      - docker.io
      # Native Firefox is much faster than the snap version, see
      # https://bugzilla.mozilla.org/show_bug.cgi?id=1748076
      - firefox
      # For GNOME system monitor shell extension.
      - gir1.2-gtop-2.0
      - gir1.2-nm-1.0
      - gir1.2-clutter-1.0
      - git
      - gnome-shell-extensions
      - gnome-system-monitor
      - google-chrome-stable
      - htop
      - libssl-dev
      - net-tools
      - php-cli
      - php-curl
      - php-gd
      - php-mbstring
      - php-simplexml
      - pkg-config
      - p7zip-full
      - python-is-python3
      # Required for dconf ansible tasks we use.
      - python3-psutil
      - qbittorrent
      - ripgrep
      - tilda
      - ttf-mscorefonts-installer
      - ubuntu-restricted-extras
      - unison-gtk
      - vim
      - vlc
      - yt-dlp
    state: present
    update_cache: "{{ firefox_ppa_prio.changed }}"
  become: yes
