---
- name: Remove APT packages we do not want
  apt:
    name:
      # Manually installing the DPKG package is annoying, use the Snap version.
      - discord
    state: absent
  become: yes

- name: Ensure old Mozilla PPA files are absent
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/preferences.d/mozillateamppa
    - /etc/apt/sources.list.d/ppa_mozillateam_ppa_noble.list
  become: yes

- name: Add Mozilla GPG key
  ansible.builtin.get_url:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x35BAA0B33E9EB396F59CA838C0BA5CE6DC6315A3&options=mr&exact=on&fingerprint=on
    dest: /etc/apt/trusted.gpg.d/mozilla.asc
    force: no
  become: yes

- name: Add Mozilla APT repository into sources list
  ansible.builtin.deb822_repository:
    name: mozilla
    types:
      - deb
    uris: https://packages.mozilla.org/apt
    suites: mozilla
    components:
      - main
    signed_by: /etc/apt/trusted.gpg.d/mozilla.asc
  become: yes

- name: Set Firefox repo priority to come first
  ansible.builtin.copy:
    content: |
      Package: *
      Pin: origin packages.mozilla.org
      Pin-Priority: 1001
    dest: /etc/apt/preferences.d/mozilla
  become: yes
  register: firefox_prio

- name: Add Chrome signing key
  ansible.builtin.get_url:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    dest: /etc/apt/trusted.gpg.d/google-chrome.asc
    force: no
  become: yes

- name: Add Google Chrome APT repository into sources list
  ansible.builtin.deb822_repository:
    name: google-chrome
    types:
      - deb
    uris: https://dl.google.com/linux/chrome/deb/
    suites: stable
    components:
      - main
    architectures: amd64
    signed_by: /etc/apt/trusted.gpg.d/google-chrome.asc
  become: yes

- name: Remove conflicting Docker packages
  apt:
    name:
      - docker.io
      - docker-compose
      - docker-compose-v2
      - docker-doc
      - podman-docker
      - containerd
      - runc
    state: absent
  become: yes

- name: Add Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/trusted.gpg.d/docker.gpg
    force: no
  become: yes

- name: Add Docker APT repository
  deb822_repository:
    name: docker
    types:
      - deb
    uris: https://download.docker.com/linux/ubuntu
    suites: "{{ ansible_distribution_release }}"
    components:
      - stable
    architectures: amd64
    signed_by: /etc/apt/trusted.gpg.d/docker.gpg
  become: yes

- name: Add DDEV signing key
  ansible.builtin.get_url:
    url: https://apt.fury.io/drud/gpg.key
    dest: /etc/apt/trusted.gpg.d/ddev.asc
    force: no
  become: yes

- name: Add DDEV APT repository into sources list
  ansible.builtin.deb822_repository:
    name: ddev
    types:
      - deb
    uris: https://apt.fury.io/drud/
    suites: "*"
    components:
      - "*"
    signed_by: /etc/apt/trusted.gpg.d/ddev.asc
  become: yes

- name: Remove old yt-dlp PPA
  ansible.builtin.apt_repository:
    repo: 'ppa:yt-dlp/stable'
    state: absent
  become: yes

- name: Add yt-dlp PPA GPG key
  ansible.builtin.get_url:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xCEC312CC5ED8215A6E0EFC49B90E9186F0E836FB&options=mr&exact=on&fingerprint=on
    dest: /etc/apt/trusted.gpg.d/yt-dlp.asc
    force: no
  become: yes

- name: Add yt-dlp PPA
  ansible.builtin.deb822_repository:
    name: yt-dlp
    types:
      - deb
    uris: https://ppa.launchpadcontent.net/tomtomtom/yt-dlp/ubuntu
    suites: "{{ ansible_distribution_release }}"
    components:
      - main
    signed_by: /etc/apt/trusted.gpg.d/yt-dlp.asc
  become: yes

- name: add vscode apt key
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/apt/trusted.gpg.d/vscode.asc
    force: no
  become: yes

- name: remove old vscode repo file
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/vscode.list
    state: absent
  become: yes

- name: add vscode repository
  ansible.builtin.deb822_repository:
    name: vscode
    types:
      - deb
    uris: https://packages.microsoft.com/repos/code
    suites: stable
    components:
      - main
    signed_by: /etc/apt/trusted.gpg.d/vscode.asc
    architectures: amd64
  become: yes

- name: add Github CLI apt key
  ansible.builtin.get_url:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    dest: /etc/apt/trusted.gpg.d/github.gpg
    force: no
  become: yes

- name: add Github CLI repository
  ansible.builtin.deb822_repository:
    name: github-cli
    types:
      - deb
    uris: https://cli.github.com/packages
    suites: stable
    components:
      - main
    architectures: amd64
    signed_by: /etc/apt/trusted.gpg.d/github.gpg
  become: yes

- name: Add PHP PPA to get PHP 8.4
  ansible.builtin.deb822_repository:
    name: ondrej-php
    types:
      - deb
    uris: https://ppa.launchpadcontent.net/ondrej/php/ubuntu
    suites: "{{ ansible_distribution_release }}"
    components:
      - main
    signed_by: /etc/apt/trusted.gpg.d/ondrej_php.asc
  become: yes

- name: Add PHP PPA GPG key
  ansible.builtin.get_url:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xB8DC7E53946656EFBCE4C1DD71DAEAAB4AD4CAB6&options=mr&exact=on&fingerprint=on
    dest: /etc/apt/trusted.gpg.d/ondrej_php.asc
    force: no
  become: yes

- name: Install Ubuntu packages we want
  apt:
    name:
      # Used for automatic background updates, see
      # https://klau.si/blog/fully-hidden-automatic-system-updates-ubuntu/
      - anacron
      - apt-transport-https
      - build-essential
      - ca-certificates
      - cmake
      - code
      - curl
      - docker-buildx-plugin
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
      - ddev
      - ffmpeg
      # Native Firefox is much faster than the snap version, see
      # https://bugzilla.mozilla.org/show_bug.cgi?id=1748076
      - firefox
      - g++
      - gcc
      - gh
      # For GNOME system monitor shell extension.
      - gir1.2-gtop-2.0
      - gir1.2-nm-1.0
      - gir1.2-clutter-1.0
      - git
      - gnome-shell-extensions
      - gnome-system-monitor
      - google-chrome-stable
      - htop
      - hunspell-de-de
      # For Rust plotters crate.
      - libfontconfig1-dev
      - libfreetype6-dev
      # For Appimage applications.
      - libfuse2
      # We need the full Libreoffice package, otherwise Libreoffice Draw
      # crashes.
      - libreoffice
      - libreoffice-calc
      - libreoffice-draw
      - libreoffice-gtk3
      - libreoffice-writer
      - libssl-dev
      - make
      - ncdu
      - nethogs
      - net-tools
      - nodejs
      - npm
      - pdftk
      - php8.4-bcmath
      - php8.4-cli
      - php8.4-curl
      - php8.4-gd
      - php8.4-gmp
      - php8.4-mbstring
      - php8.4-simplexml
      - php8.4-zip
      - pkg-config
      - p7zip-full
      - pwgen
      - python-is-python3
      # Required for dconf ansible tasks we use.
      - python3-psutil
      - qbittorrent
      - ripgrep
      - tilda
      - ttf-mscorefonts-installer
      - ubuntu-restricted-extras
      - unison-gtk
      - vim
      - libxml2-utils
      - vlc
      - xsel
      - yt-dlp
    state: present
    update_cache: "{{ firefox_prio.changed }}"
  become: yes
