---
- name: Remove APT packages we do not want
  apt:
    name:
      # Manually installing the DPKG package is annoying, use the Snap version.
      - discord
    state: absent
  become: yes

- name: Add Mozilla Team PPA for Firefox APT version
  apt_repository:
    repo: 'ppa:mozillateam/ppa'
  become: yes

- name: Add Mozilla PPA GPG key
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: 0AB215679C571D1C8325275B9BDB3D89CE49EC21
    keyring: /etc/apt/trusted.gpg.d/mozilla.gpg
  become: yes

- name: Set Firefox PPA priority to come first
  ansible.builtin.copy:
    content: |
      Package: *
      Pin: release o=LP-PPA-mozillateam
      Pin-Priority: 1001
    dest: /etc/apt/preferences.d/mozillateamppa
  become: yes
  register: firefox_ppa_prio

- name: Add Chrome signing key
  ansible.builtin.apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    id: EB4C1BFD4F042F6DDDCCEC917721F63BD38B4796
    keyring: /etc/apt/trusted.gpg.d/google-chrome.gpg
  become: yes

- name: Add Google Chrome APT repository into sources list
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome
  become: yes

- name: Add Git PPA to get autoSetupRemote support
  apt_repository:
    repo: 'ppa:git-core/ppa'
  become: yes

- name: Add Git PPA GPG key
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: E1DD270288B4E6030699E45FA1715D88E1DF1F24
    keyring: /etc/apt/trusted.gpg.d/git.gpg
  become: yes

- name: Add DDEV signing key
  ansible.builtin.apt_key:
    url: https://apt.fury.io/drud/gpg.key
    id: DBD730A3A581BDAC98BAF17FC16711FC1179C7CA
    keyring: /etc/apt/trusted.gpg.d/ddev.gpg
  become: yes

- name: Add DDEV APT repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://apt.fury.io/drud/ * *
    state: present
    filename: ddev
  become: yes

- name: Remove old yt-dlp PPA
  apt_repository:
    repo: 'ppa:yt-dlp/stable'
    state: absent
  become: yes

- name: Add yt-dlp PPA
  apt_repository:
    repo: 'ppa:tomtomtom/yt-dlp'
  become: yes

- name: Add yt-dlp PPA GPG key
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: CEC312CC5ED8215A6E0EFC49B90E9186F0E836FB
    keyring: /etc/apt/trusted.gpg.d/yt-dlp.gpg
  become: yes

- name: add vscode apt key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /etc/apt/trusted.gpg.d/vscode.gpg
    id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
  become: yes

- name: remove old vscode repo file
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/packages_microsoft_com_repos_code.list
    state: absent
  become: yes

- name: add vscode repository
  apt_repository:
    repo: deb [arch=amd64,arm64,armhf] http://packages.microsoft.com/repos/code stable main
    filename: vscode
  become: yes

- name: add Github CLI apt key
  apt_key:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    keyring: /etc/apt/trusted.gpg.d/github.gpg
    id: 2C6106201985B60E6C7AC87323F3D4EA75716059
  become: yes

- name: add Github CLI repository
  apt_repository:
    repo: "deb [arch=amd64] https://cli.github.com/packages stable main"
    filename: github-cli
  become: yes

- name: Install Ubuntu packages we want
  apt:
    name:
      # Used for automatic background updates, see
      # https://klau.si/blog/fully-hidden-automatic-system-updates-ubuntu/
      - anacron
      - apt-transport-https
      - build-essential
      - cmake
      - code
      - curl
      - ddev
      - docker.io
      # Native Firefox is much faster than the snap version, see
      # https://bugzilla.mozilla.org/show_bug.cgi?id=1748076
      - firefox
      - g++
      - gcc
      - gh
      # For GNOME system monitor shell extension.
      - gir1.2-gtop-2.0
      - gir1.2-nm-1.0
      - gir1.2-clutter-1.0
      - git
      - gnome-shell-extensions
      - gnome-system-monitor
      - google-chrome-stable
      - htop
      # For Rust plotters crate.
      - libfontconfig1-dev
      - libfreetype6-dev
      # For Appimage applications.
      - libfuse2
      # We need the full Libreoffice package, otherwise Libreoffice Draw
      # crashes.
      - libreoffice
      - libreoffice-calc
      - libreoffice-draw
      - libreoffice-gtk3
      - libreoffice-writer
      - libssl-dev
      - make
      - ncdu
      - net-tools
      - nodejs
      - npm
      - pdftk
      - php-cli
      - php-curl
      - php-gd
      - php-mbstring
      - php-simplexml
      - pkg-config
      - p7zip-full
      - pwgen
      - python-is-python3
      # Required for dconf ansible tasks we use.
      - python3-psutil
      - qbittorrent
      - ripgrep
      - tilda
      - ttf-mscorefonts-installer
      - ubuntu-restricted-extras
      - unison-gtk
      - vim
      - libxml2-utils
      - vlc
      - yt-dlp
    state: present
    update_cache: "{{ firefox_ppa_prio.changed }}"
  become: yes
