---
- name: Hide GNOME desktop icons
  community.general.dconf:
    key: "/org/gnome/shell/disabled-extensions"
    value: "['ding@rastersoft.com']"

- name: Set a list of GNOME extension we want
  set_fact:
    extensions:
      system-monitor-next@paradoxxx.zero.gmail.com: https://extensions.gnome.org/extension-data/system-monitor-nextparadoxxx.zero.gmail.com.v42.shell-extension.zip
      openweather-extension@penguin-teal.github.io: https://extensions.gnome.org/extension-data/openweather-extensionpenguin-teal.github.io.v13.shell-extension.zip
      Hide_Activities@shay.shayel.org: https://extensions.gnome.org/extension-data/Hide_Activitiesshay.shayel.org.v13.shell-extension.zip

- name: Ensure GNOME extension directories exist
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/share/gnome-shell/extensions/{{ item.key }}"
    state: directory
  loop: "{{ extensions|dict2items }}"

- name: Install GNOME extensions
  ansible.builtin.unarchive:
    src: "{{ item.value }}"
    dest: "{{ lookup('env', 'HOME') }}/.local/share/gnome-shell/extensions/{{ item.key }}"
    creates: "{{ lookup('env', 'HOME') }}/.local/share/gnome-shell/extensions/{{ item.key }}/metadata.json"
    remote_src: yes
  loop: "{{ extensions|dict2items }}"

- name: Set enabled GNOME extensions
  community.general.dconf:
    key: "/org/gnome/shell/enabled-extensions"
    value: "['Hide_Activities@shay.shayel.org', 'system-monitor-next@paradoxxx.zero.gmail.com', 'openweather-extension@penguin-teal.github.io']"

- name: Set weather temperature decimal point
  community.general.dconf:
    key: "/org/gnome/shell/extensions/openweather/decimal-places"
    value: "0"

- name: Set weather location
  community.general.dconf:
    key: "/org/gnome/shell/extensions/openweather/city"
    value: "'48.2083537,16.3725042>Wien, 1010, Österreich >0'"

- name: Move Dock to the right
  community.general.dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/dock-position"
    value: "'RIGHT'"

- name: Set Shutdown shortcut binding
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding"
    value: "'<Primary><Alt>h'"

- name: Set Shutdown shortcut command
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command"
    value: "'gnome-session-quit --power-off --force'"

- name: Set Shutdown shortcut name
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name"
    value: "'Shutdown Halt'"

- name: Set Tilda shortcut binding
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding"
    value: "'F12'"

- name: Set Tilda shortcut command
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command"
    value: "'tilda --dbus -T 0'"

- name: Set Tilda shortcut name
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name"
    value: "'Tilda toggle'"

- name: Set custom keybinding shortcuts
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
    value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/','/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/']"

- name: Disable touchpad tap dragging, I trigger it a lot by accident
  community.general.dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/tap-and-drag"
    value: "false"

- name: Nautilus file manager default list-view
  community.general.dconf:
    key: "/org/gnome/nautilus/preferences/default-folder-viewer"
    value: "'list-view'"

- name: Set Dash to Dock click action to cycle windows
  community.general.dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/click-action"
    value: "'cycle-windows'"

- name: Set text editor highlight-current-line
  community.general.dconf:
    key: "/org/gnome/TextEditor/highlight-current-line"
    value: "true"

- name: Set text editor ident-style
  community.general.dconf:
    key: "/org/gnome/TextEditor/indent-style"
    value: "'space'"

- name: Set text editor show-line-numbers
  community.general.dconf:
    key: "/org/gnome/TextEditor/show-line-numbers"
    value: "true"

- name: Set text editor show-right-margin
  community.general.dconf:
    key: "/org/gnome/TextEditor/show-right-margin"
    value: "true"

- name: Set text editor tab-width
  community.general.dconf:
    key: "/org/gnome/TextEditor/tab-width"
    value: "uint32 2"

- name: Disable caps lock
  community.general.dconf:
    key: "/org/gnome/desktop/input-sources/xkb-options"
    value: "['caps:none']"

- name: Disable touchpad right click
  community.general.dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/click-method"
    value: "'none'"
