---
- name: Ensuring Homebrew Is installed
  stat:
    path: /home/linuxbrew/.linuxbrew/bin/brew
  register: homebrew_check

- name: Installing Homebrew
  when: not homebrew_check.stat.exists
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

- name: Ensure Homebrew activated in .profile
  ansible.builtin.lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.profile"
    line: 'eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)'

- name: Installing Homebrew Packages
  # When brew is freshly installed it is not available on the PATH yet, ensure
  # it is there manually.
  environment:
    PATH: /home/linuxbrew/.linuxbrew/bin:{{ ansible_env.PATH }}
  homebrew:
    name:
      - drud/ddev/ddev
      - ripgrep
      - starship
      - yt-dlp
    state: present

- name: Removing Homebrew Packages
  # When brew is freshly installed it is not available on the PATH yet, ensure
  # it is there manually.
  environment:
    PATH: /home/linuxbrew/.linuxbrew/bin:{{ ansible_env.PATH }}
  homebrew:
    name:
      # Zola image linking is broken, install old version manually.
      # https://github.com/getzola/zola/issues/1772
      - zola
    state: absent

- name: Install old Zola version
  ansible.builtin.unarchive:
    src: "https://github.com/getzola/zola/releases/download/v0.14.1/zola-v0.14.1-x86_64-unknown-linux-gnu.tar.gz"
    dest: "{{ lookup('env', 'HOME') }}/.local/bin"
    creates: "{{ lookup('env', 'HOME') }}/.local/bin/zola"
    remote_src: yes
