---
- name: Ensure fonts directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.fonts"
    state: directory

- name: Download Nerd font
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraCode.zip
    dest: "{{ lookup('env', 'HOME') }}/.fonts/"
    remote_src: yes
    creates: "{{ lookup('env', 'HOME') }}/.fonts/Fira\ Code\ Regular\ Nerd\ Font\ Complete.ttf"
  register: nerd_font_installed

- name: Rebuild font cache
  when: nerd_font_installed.changed
  shell: fc-cache -fv

- name: Install the Starship Rust package with locked dependencies
  community.general.cargo:
    name: starship

- name: Ensure Starship activated in .bashrc
  ansible.builtin.lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.bashrc"
    line: 'eval "$(starship init bash)"'

- name: Put Starship config into place
  ansible.builtin.copy:
    src: starship.toml
    dest: "{{ lookup('env', 'HOME') }}/.config/starship.toml"
