---
- name: Ensure tilda config dir exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/tilda"
    state: directory

- name: Put Tilda config into place with Nerd font
  ansible.builtin.copy:
    src: tilda.ini
    dest: "{{ lookup('env', 'HOME') }}/.config/tilda/config_0"

- name: Put Tilda CSS into place for better tab visibility
  ansible.builtin.copy:
    src: tilda.css
    dest: "{{ lookup('env', 'HOME') }}/.config/tilda/style.css"

- name: Ensure autostart config dir exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/autostart"
    state: directory

- name: Put Tilda autostart config into place
  ansible.builtin.copy:
    src: tilda.desktop
    dest: "{{ lookup('env', 'HOME') }}/.config/autostart/tilda.desktop"
