---
- name: Ensure .local/bin dir exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/bin"
    state: directory

- name: Install Topgrade
  ansible.builtin.unarchive:
    src: https://github.com/r-darwish/topgrade/releases/download/v8.2.0/topgrade-v8.2.0-x86_64-unknown-linux-gnu.tar.gz
    dest: "{{ lookup('env', 'HOME') }}/.local/bin/"
    remote_src: yes
    creates: "{{ lookup('env', 'HOME') }}/.local/bin/topgrade"

# Gcloud is udpated with snaps, do not upgrade it.
- name: Disable gcloud update in Topgrade
  ansible.builtin.copy:
    content: 'disable = ["gcloud", "containers", "composer"]'
    dest: "{{ lookup('env', 'HOME') }}/.config/topgrade.toml"
