---
- name: Install Topgrade
  ansible.builtin.get_url:
    url: https://github.com/topgrade-rs/topgrade/releases/download/v10.2.4/topgrade-v10.2.4-x86_64-unknown-linux-gnu.tar.gz
    dest: "{{ lookup('env', 'HOME') }}/.local/bin/topgrade"
    mode: '0755'
    force: no

- name: Put Topgrade config into place
  ansible.builtin.copy:
    src: topgrade.toml
    dest: "{{ lookup('env', 'HOME') }}/.config/topgrade.toml"
