---
- name: Install Topgrade
  ansible.builtin.unarchive:
    src: https://github.com/r-darwish/topgrade/releases/download/v8.2.0/topgrade-v8.2.0-x86_64-unknown-linux-gnu.tar.gz
    dest: "{{ lookup('env', 'HOME') }}/.local/bin/"
    remote_src: yes
    creates: "{{ lookup('env', 'HOME') }}/.local/bin/topgrade"

- name: Put Topgrade config into place
  ansible.builtin.copy:
    src: topgrade.toml
    dest: "{{ lookup('env', 'HOME') }}/.config/topgrade.toml"
