---
- name: Install Topgrade
  ansible.builtin.unarchive:
    src: https://github.com/topgrade-rs/topgrade/releases/download/v10.2.4/topgrade-v10.2.4-x86_64-unknown-linux-gnu.tar.gz
    dest: "{{ lookup('env', 'HOME') }}/.local/bin"
    remote_src: yes
    creates: "{{ lookup('env', 'HOME') }}/.local/bin/topgrade"

- name: Put Topgrade config into place
  ansible.builtin.copy:
    src: topgrade.toml
    dest: "{{ lookup('env', 'HOME') }}/.config/topgrade.toml"
