---
- name: Remove Snap packages we do not want
  community.general.snap:
    name:
      # The Snap version of VSCode cannot open links.
      - code
      # Firefox via Snap is super slow on cold starts, install the APT
      # version below instead.
      - firefox
      # The APT version of LibreOffice ist faster and works with my extensions
      # again.
      - libreoffice
      # We don't need the graphical snap store and it makes problems with
      # auto-updating snaps.
      - snap-store
      # Starship is outdated in Snap, so we install it with cargo instead.
      - starship
    state: absent
  become: yes

- name: Install Snap packages we want
  community.general.snap:
    name:
      - joplin-desktop
      - yq
      - zoom-client
  become: yes

- name: Install Snap packages in edge mode that we want
  community.general.snap:
    name:
      - zola
    channel: edge
  become: yes

- name: Put auto APT script into place for Anacron
  ansible.builtin.copy:
    src: autoapt.sh
    dest: /etc/cron.daily/autoapt
    mode: preserve
  become: yes

- name: Disable APT systemd timer
  ansible.builtin.systemd:
    name: apt-daily.timer
    enabled: no
    state: stopped
  become: yes

- name: Disable APT upgrade systemd timer
  ansible.builtin.systemd:
    name: apt-daily-upgrade.timer
    enabled: no
    state: stopped
  become: yes

- name: Make Firefox the default browser
  community.general.alternatives:
    name: x-www-browser
    path: /usr/bin/firefox
  become: yes

- name: Ensure .local/bin directory exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/bin"
    state: directory

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    groups: docker
    append: yes
  become: yes

- name: Set a list of Bash aliases
  set_fact:
    bash_aliases:
      ag: rg
      copilot: "gh copilot"
      drupalorg: "{{ lookup('env', 'HOME') }}/workspace/drupalorg-cli/drupalorg"
      gce: "gh copilot explain"
      c: "gh copilot suggest -t shell"
      pareview.sh: "{{ lookup('env', 'HOME') }}/workspace/pareviewsh/pareview.sh"
      s: "{{ lookup('env', 'HOME') }}/workspace/ce_scripts/helpers/ssh_connect.sh"

- name: Set aliases in .bashrc
  ansible.builtin.lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.bashrc"
    line: "alias {{ item.key }}='{{ item.value }}'"
  loop: "{{ bash_aliases|dict2items }}"

- name: Include Github copilot aliases
  ansible.builtin.lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.bashrc"
    line: 'eval "$(gh copilot alias -- bash)"'

- name: Remove Canonical spam advertisements in APT output
  ansible.builtin.copy:
    content: ""
    dest: /etc/apt/apt.conf.d/20apt-esm-hook.conf
  become: yes

- name: Show raw system output on Ubuntu startup instead of splash screen
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT=""'
  become: yes
  register: grub_splash

- name: Update GRUB if needed
  shell: update-grub
  become: yes
  when: grub_splash.changed

- name: Ensure mkcert is installed
  ansible.builtin.shell:
    cmd: "mkcert -install"
    creates: /home/klausi/.local/share/mkcert

- name: Install Composer
  ansible.builtin.shell:
    cmd: "curl -sS https://getcomposer.org/installer | php -- --install-dir={{ lookup('env', 'HOME') }}/.local/bin --filename=composer"
    creates: "{{ lookup('env', 'HOME') }}/.local/bin/composer"

- name: Copy default apps for xdg-settings
  ansible.builtin.copy:
    src: mimeapps.list
    dest: "{{ lookup('env', 'HOME') }}/.config/mimeapps.list"

- name: Ensure de_AT locale entry exists (uncomment/add line)
  ansible.builtin.lineinfile:
    path: /etc/locale.gen
    regexp: '^#?de_AT\.UTF-8\s+UTF-8'
    line: 'de_AT.UTF-8 UTF-8'
    state: present
  become: yes
  register: de_at_locale

- name: Set LC_TIME to de_AT.utf8
  ansible.builtin.lineinfile:
    path: /etc/default/locale
    regexp: '^LC_TIME='
    line: 'LC_TIME=de_AT.utf8'
    create: yes
  become: yes

- name: Generate DE locale
  become: yes
  ansible.builtin.command: locale-gen de_AT.UTF-8
  when: de_at_locale.changed
