---
- name: Remove Snap packages we do not want
  community.general.snap:
    name:
      # Firefox via Snap is super slow on cold starts, install the APT
      # version below instead.
      - firefox
    state: absent
  become: yes

- name: Add Mozilla Team PPA for Firefox APT version
  apt_repository:
    repo: 'ppa:mozillateam/ppa'
  become: yes

- name: Set Firefox PPA priority to come first
  ansible.builtin.copy:
    content: |
      Package: *
      Pin: release o=LP-PPA-mozillateam
      Pin-Priority: 1001
    dest: /etc/apt/preferences.d/mozillateamppa
  become: yes
  register: firefox_ppa_prio

- name: Add Chrome signing key
  ansible.builtin.apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
  become: yes

- name: Add Google Chrome APT repository into sources list
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome
  become: yes

- name: Install Ubuntu packages we want
  apt:
    name:
      # Used for automatic background updates, see
      # https://klau.si/blog/fully-hidden-automatic-system-updates-ubuntu/
      - anacron
      - build-essential
      - curl
      # Native Firefox is much faster than the snap version, see
      # https://bugzilla.mozilla.org/show_bug.cgi?id=1748076
      - firefox
      - google-chrome-stable
      # Required for dconf ansible tasks we use.
      - python3-psutil
      - tilda
      - vim
    state: present
    update_cache: "{{ firefox_ppa_prio.changed }}"
  become: yes

- name: Install Snap packages we want
  community.general.snap:
    name:
      - zoom-client
  become: yes

- name: Install Snap packages in classic mode that we want
  community.general.snap:
    name:
      - code
    classic: yes
  become: yes

- name: Put auto APT script into place for Anacron
  ansible.builtin.copy:
    src: autoapt.sh
    dest: /etc/cron.daily/autoapt
    mode: preserve
  become: yes

- name: Make Firefox the default browser
  community.general.alternatives:
    name: x-www-browser
    path: /usr/bin/firefox
  become: yes

- name: Ensure .local/bin directory exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/bin"
    state: directory
